### ISSUE TITLE
Fix bug that happens after cancelling record creation

### ISSUE THREAD

**Issue by ConstantinLange** [HPI-SWA-Teaching/SWT17-Project-09#29]
--> Record existiert
--> neues Erstellen
--> Oh ja mach ich
--> Nein doch nicht | Cancel
--> Fehler wird geworfen.

**Comment by fyndalf** [comment]
The error that gets thrown is a generic error message saying `Please close this to abort file opening`. The responsible method is a part of the standard `FileStream`, so I don't see a way around it. Any ideas? @ConstantinLange @tom-lichtenstein @fswt

**Comment by fyndalf** [comment]
Exception can be caught via [block closure] on: (Error) do: []
